### ISSUE TITLE
Tracking issue: CI release improvements

### ISSUE THREAD

**Issue by VorpalBlade** [VorpalBlade/paketkoll#4]
* [x] Update AUR when building release (adapt code from chezmoi_modify_manager)
* [x] Fix upstream bugs in release-plz making it less than ideal.
* [x] Integrate release-plz in CI (need to look into how exactly this works).
