### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by VorpalBlade** [VorpalBlade/paketkoll#50]
* [ ] Mtime disk cache for Debian (see #45)
* [ ] Disk cache: refresh on access?
* [ ] Disk cache - sled: Too many IO threads?
* [ ] Tweak heuristics in `fs_load_contents`
* [ ] Look into map types (ahashmap vs btreemap, dashmap vs concurrent-map etc)
  Especially important for building the package ID to package map, which cannot use dashmap due to lack of covariance. 
* [ ] Files backend builds packages internally :(
* [ ] mtree2: what about `&mut` for smallvec/vec?
* [ ] Build performance: Move cli into sub-crates so xtask is cheaper for paketkoll-only builds (for AUR packages this matters)
