### ISSUE TITLE
Clean up output formatting of konfigkoll

### ISSUE THREAD

**Issue by VorpalBlade** [VorpalBlade/paketkoll#53]
* [ ] A nicer tracing-subscriber format
* [ ] Add Rune API for structured logging
* [ ] Clean up some of the debug output to show the user what is really important
